[postgresql]
host=127.0.0.1
port=5432
database=shops_sim
user=postgres
password=123


[paths]
# Папка, где будут лежать CSV файлы
data_dir=data

[network]
shops_count=10 # Количество магазинов в сети.
cashes_per_shop=4 # Максимальное количество касс в каждом магазине. Но не все кассы будут активными каждый день.


[categories]
list=Бытовая химия,Хозтовары,Текстиль,Посуда,Мебель

[items]
Бытовая химия=Стиральный порошок,Шампунь,Мыло
Хозтовары=Ведро,Веник,Губки для посуды,Пакеты для мусора
Текстиль=Подушка,Полотенце,Скатерть,Постельное белье,Шторы
Посуда=Тарелка,Нож,Кастрюля
Мебель=Стол,Стул,Шкаф,Кровать,Диван